# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 04:23
from __future__ import unicode_literals

import deepzoom.mixins
import deepzoom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deepzoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(height_field=b'height', max_length=512, upload_to=deepzoom.models.get_uploaded_image_root, width_field=b'width')),
                ('name', models.CharField(help_text=b'Max 128 characters.', max_length=128, unique=True)),
                ('slug', models.SlugField(editable=False, help_text=b'(system-constructed)', max_length=128)),
                ('height', models.PositiveIntegerField(editable=False, help_text=b'(system-calculated)')),
                ('width', models.PositiveIntegerField(editable=False, help_text=b'(system-calculated)')),
                ('create_deepzoom', models.BooleanField(default=False, help_text=b'Generate deep zoom?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mission', models.CharField(blank=True, max_length=225, null=True)),
                ('role', models.CharField(blank=True, max_length=225, null=True)),
                ('frame', models.CharField(blank=True, max_length=225, null=True)),
                ('associated_deepzoom', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='georef_myimage', to='deepzoom.DeepZoom')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'get_latest_by': 'created',
            },
            bases=(deepzoom.mixins.ModelDiffMixin, models.Model),
        ),
    ]
