# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 22:23
from __future__ import unicode_literals

import deepzoom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='frame',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='myimage',
            name='mission',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='myimage',
            name='role',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='uploaded_image',
            field=models.ImageField(height_field=b'height', max_length=512, upload_to=deepzoom.models.get_uploaded_image_root, width_field=b'width'),
        ),
    ]
